import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ProductCard from "@/components/ProductCard";
import Banner from "@/components/Banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  console.log("ppp", posts);
  return (
    <>
      <Head>
        <title>Pc Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.container}`}>
          {" "}
          <Banner />
          <div className={`${styles.home_product}`}>
            {posts?.data?.map((post) => {
              return <ProductCard key={post?._id} data={post} />;
            })}
          </div>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://pc-builder-sand.vercel.app/api/v1/product");
  const posts = await res.json();

  console.log("rrrr", posts);

  return {
    props: {
      posts,
    },
  };
}
